name: Create Core and Example Releases

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Debug: List repository contents
      - name: List repository contents
        run: |
          ls -R
        shell: bash

      # Extract README sections
      - name: Extract README sections
        run: |
          mkdir -p temp
          awk '/<!-- BEGIN FEATURES -->/{p=1}/<!-- END FEATURES -->/{p=0}p' README.md > temp/Features.md
          awk '/<!-- BEGIN REQUIREMENTS -->/{p=1}/<!-- END REQUIREMENTS -->/{p=0}p' README.md > temp/Requirements.md
          awk '/<!-- BEGIN INSTALLATION -->/{p=1}/<!-- END INSTALLATION -->/{p=0}p' README.md > temp/Installation.md
          awk '/<!-- BEGIN CONFIG -->/{p=1}/<!-- END CONFIG -->/{p=0}p' README.md > temp/Config.md
          awk '/<!-- BEGIN EXAMPLES -->/{p=1}/<!-- END EXAMPLES -->/{p=0}p' README.md > temp/Examples.md
          awk '/<!-- BEGIN TROUBLESHOOTING -->/{p=1}/<!-- END TROUBLESHOOTING -->/{p=0}p' README.md > temp/Troubleshooting.md
          awk '/<!-- BEGIN WINDOWS -->/{p=1}/<!-- END WINDOWS -->/{p=0}p' README.md > temp/Windows.md
          awk '/<!-- BEGIN LICENSE -->/{p=1}/<!-- END LICENSE -->/{p=0}p' README.md > temp/License.md
          # Verify extracted files
          for file in temp/*.md; do
            if [ ! -s "$file" ]; then
              echo "Error: $file is empty or missing"
              exit 1
            fi
          done
        shell: bash

      # Create core release zip
      - name: Create core release zip
        run: |
          basepath=tikzexternal-autocache-core-${{ github.event.release.tag_name }}
          mkdir -p ${basepath}/texmf/tex/latex
          cp src/tikzlibraryexternal-autocache.code.tex ${basepath}/texmf/tex/latex/
          # Replace placeholders in tikzlibraryexternal-autocache.code.tex
          current_date=$(date -u +%Y/%m/%d)
          version=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          sed -i "s/{{DATE}}/$current_date/" ${basepath}/texmf/tex/latex/tikzlibraryexternal-autocache.code.tex
          sed -i "s/{{VERSION}}/$version/" ${basepath}/texmf/tex/latex/tikzlibraryexternal-autocache.code.tex
          # Verify template exists
          if [ ! -f src/README.tpl.md ]; then
            echo "Error: src/README.tpl.md not found"
            exit 1
          fi
          # Generate README-external-autocache.md from template
          cp src/README.tpl.md ${basepath}/README-external-autocache.md
          echo "# Ti*k*Z External Autocache (${{ github.event.release.tag_name }})" > temp/core_preamble.md
          echo "" >> temp/core_preamble.md
          echo "This is the core Ti*k*Z external autocache library release, containing the library file for drop-in use." >> temp/core_preamble.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ Preamble }}/, p)}1' temp/core_preamble.md ${basepath}/README-external-autocache.md > temp/core_temp1.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ FEATURES }}/, p)}1' temp/Features.md temp/core_temp1.md > temp/core_temp2.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ REQUIREMENTS }}/, p)}1' temp/Requirements.md temp/core_temp2.md > temp/core_temp3.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ INSTALLATION }}/, p)}1' temp/Installation.md temp/core_temp3.md > temp/core_temp4.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ CONFIG }}/, p)}1' temp/Config.md temp/core_temp4.md > temp/core_temp5.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ TROUBLESHOOTING }}/, p)}1' temp/Troubleshooting.md temp/core_temp5.md > temp/core_temp6.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ LICENSE }}/, p)}1' temp/License.md temp/core_temp6.md > ${basepath}/README-external-autocache.md
          # Add release tag comments
          for file in ${basepath}/texmf/tex/latex/*.tex; do
            echo "% Release: ${{ github.event.release.tag_name }}" | cat - "$file" > temp/tex_temp && mv temp/tex_temp "$file"
          done
          for file in ${basepath}/*.md; do
            echo "<!-- Release: ${{ github.event.release.tag_name }} -->" | cat - "$file" > temp/md_temp && mv temp/md_temp "$file"
          done
          # Replace {{TAG}} in Markdown
          find ${basepath} -type f -name "*.md" -exec sed -i "s/{{TAG}}/${{ github.event.release.tag_name }}/g" {} \;
          # Debug: Verify files
          cat ${basepath}/README-external-autocache.md
          cat ${basepath}/texmf/tex/latex/tikzlibraryexternal-autocache.code.tex
          zip -r tikzexternal-autocache-core.zip ${basepath}
        shell: bash

      # Create example release zip
      - name: Create example release zip
        run: |
          basepath=tikzexternal-autocache-example-${{ github.event.release.tag_name }}
          mkdir -p ${basepath}/{.devcontainer,texmf/tex/latex,src/example-directory}
          cp -r .devcontainer/* ${basepath}/.devcontainer/
          cp -r example/{main1.tex,main2.tex,latexmkrc,.gitattributes,.gitignore} ${basepath}/
          cp -r example/src/example-directory/{equations.tikz,image.tikz} ${basepath}/src/example-directory/
          cp src/tikzlibraryexternal-autocache.code.tex ${basepath}/texmf/tex/latex/
          cp .gitattributes ${basepath}/
          cp .gitignore ${basepath}/
          # Replace placeholders in tikzlibraryexternal-autocache.code.tex
          current_date=$(date -u +%Y/%m/%d)
          version=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          sed -i "s/{{DATE}}/$current_date/" ${basepath}/texmf/tex/latex/tikzlibraryexternal-autocache.code.tex
          sed -i "s/{{VERSION}}/$version/" ${basepath}/texmf/tex/latex/tikzlibraryexternal-autocache.code.tex
          # Verify template exists
          if [ ! -f example/README.tpl.md ]; then
            echo "Error: example/README.tpl.md not found"
            exit 1
          fi
          # Generate README-external-autocache.md from template
          cp example/README.tpl.md ${basepath}/README-external-autocache.md
          echo "# Ti*k*Z External Autocache (${{ github.event.release.tag_name }})" > temp/example_preamble.md
          echo "" >> temp/example_preamble.md
          echo "This is the example Ti*k*Z external autocache release, including demo files and a development environment." >> temp/example_preamble.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ Preamble }}/, p)}1' temp/example_preamble.md ${basepath}/README-external-autocache.md > temp/example_temp1.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ INSTALLATION }}/, p)}1' temp/Installation.md temp/example_temp1.md > temp/example_temp2.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ EXAMPLES }}/, p)}1' temp/Examples.md temp/example_temp2.md > temp/example_temp3.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ TROUBLESHOOTING }}/, p)}1' temp/Troubleshooting.md temp/example_temp3.md > temp/example_temp4.md
          awk 'NR==FNR {p=p $0 "\n"; next} {sub(/{{ WINDOWS }}/, p)}1' temp/Windows.md temp/example_temp4.md > ${basepath}/README-external-autocache.md
          # Add release tag comments
          for file in ${basepath}/*.tex ${basepath}/texmf/tex/latex/*.tex ${basepath}/.devcontainer/*.json; do
            echo "% Release: ${{ github.event.release.tag_name }}" | cat - "$file" > temp/tex_json_temp && mv temp/tex_json_temp "$file"
          done
          for file in ${basepath}/*.md ${basepath}/.devcontainer/*.md; do
            echo "<!-- Release: ${{ github.event.release.tag_name }} -->" | cat - "$file" > temp/md_temp && mv temp/md_temp "$file"
          done
          for file in ${basepath}/*.rc ${basepath}/.devcontainer/*.{yml,yaml}; do
            echo "# Release: ${{ github.event.release.tag_name }}" | cat - "$file" > temp/rc_yml_temp && mv temp/rc_yml_temp "$file"
          done
          # Replace {{TAG}} in Markdown (not in .devcontainer files)
          find ${basepath} -type f -name "*.md" -not -path "${basepath}/.devcontainer/*" -exec sed -i "s/{{TAG}}/${{ github.event.release.tag_name }}/g" {} \;
          # Debug: Verify files
          cat ${basepath}/README-external-autocache.md
          cat ${basepath}/texmf/tex/latex/tikzlibraryexternal-autocache.code.tex
          cat ${basepath}/.devcontainer/devcontainer.json
          rm -rf temp
          zip -r tikzexternal-autocache-example.zip ${basepath}
        shell: bash

      # Upload core release zip
      - name: Upload core release zip
        run: |
          gh release upload ${{ github.event.release.tag_name }} tikzexternal-autocache-core.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      # Upload example release zip
      - name: Upload example release zip
        run: |
          gh release upload ${{ github.event.release.tag_name }} tikzexternal-autocache-example.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
